package clang.decl

// BEGIN KRAPPER GEN for enum Kind
enum class Kind(val value: UInt) {
    TranslationUnit(0u), TopLevelStmt(1u), RequiresExprBody(2u), OutlinedFunction(3u), LinkageSpec(4u), ExternCContext(5u), Export(6u), Captured(7u), Block(8u), StaticAssert(9u), PragmaDetectMismatch(10u), PragmaComment(11u), OpenACCRoutine(12u), OpenACCDeclare(13u), ObjCPropertyImpl(14u), OMPThreadPrivate(15u), OMPRequires(16u), OMPGroupPrivate(17u), OMPAllocate(18u), ObjCMethod(19u), ObjCProtocol(20u), ObjCInterface(21u), ObjCImplementation(22u), ObjCCategoryImpl(23u), firstObjCImpl(22u), lastObjCImpl(23u), ObjCCategory(24u), firstObjCContainer(20u), lastObjCContainer(24u), HLSLBuffer(25u), OMPDeclareReduction(26u), OMPDeclareMapper(27u), UnresolvedUsingValue(28u), UnnamedGlobalConstant(29u), TemplateParamObject(30u), MSGuid(31u), IndirectField(32u), EnumConstant(33u), Function(34u), CXXMethod(35u), CXXDestructor(36u), CXXConversion(37u), CXXConstructor(38u), firstCXXMethod(35u), lastCXXMethod(38u), CXXDeductionGuide(39u), firstFunction(34u), lastFunction(39u), Var(40u), VarTemplateSpecialization(41u), VarTemplatePartialSpecialization(42u), firstVarTemplateSpecialization(41u), lastVarTemplateSpecialization(42u), ParmVar(43u), OMPCapturedExpr(44u), ImplicitParam(45u), Decomposition(46u), firstVar(40u), lastVar(46u), NonTypeTemplateParm(47u), MSProperty(48u), Field(49u), ObjCIvar(50u), ObjCAtDefsField(51u), firstField(49u), lastField(51u), firstDeclarator(34u), lastDeclarator(51u), Binding(52u), firstValue(26u), lastValue(52u), UsingShadow(53u), ConstructorUsingShadow(54u), firstUsingShadow(53u), lastUsingShadow(54u), UsingPack(55u), UsingDirective(56u), UnresolvedUsingIfExists(57u), Record(58u), CXXRecord(59u), ClassTemplateSpecialization(60u), ClassTemplatePartialSpecialization(61u), firstClassTemplateSpecialization(60u), lastClassTemplateSpecialization(61u), firstCXXRecord(59u), lastCXXRecord(61u), firstRecord(58u), lastRecord(61u), Enum(62u), firstTag(58u), lastTag(62u), UnresolvedUsingTypename(63u), Typedef(64u), TypeAlias(65u), ObjCTypeParam(66u), firstTypedefName(64u), lastTypedefName(66u), TemplateTypeParm(67u), firstType(58u), lastType(67u), TemplateTemplateParm(68u), VarTemplate(69u), TypeAliasTemplate(70u), FunctionTemplate(71u), ClassTemplate(72u), firstRedeclarableTemplate(69u), lastRedeclarableTemplate(72u), Concept(73u), BuiltinTemplate(74u), firstTemplate(68u), lastTemplate(74u), ObjCProperty(75u), ObjCCompatibleAlias(76u), Namespace(77u), NamespaceAlias(78u), firstNamespaceBase(77u), lastNamespaceBase(78u), Label(79u), HLSLRootSignature(80u), UsingEnum(81u), Using(82u), firstBaseUsing(81u), lastBaseUsing(82u), firstNamed(19u), lastNamed(82u), LifetimeExtendedTemporary(83u), Import(84u), ImplicitConceptSpecialization(85u), FriendTemplate(86u), Friend(87u), FileScopeAsm(88u), Empty(89u), AccessSpec(90u), firstDecl(0u), lastDecl(90u);

    companion object {
        fun fromValue(v: UInt): Kind = entries.firstOrNull { it.value == v } ?: entries.first()
    }
}
// END KRAPPER GEN for enum Kind
