/*
 * Copyright 2026 Jason Monk
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import geo.Point
import geo.Point.Companion.Point
import geo.Rect
import geo.Rect.Companion.Rect
import kotlinx.cinterop.memScoped

// A first-contact kplusplus program: it drives the bindings generated for
// cpp/geometry.h. Read that header alongside this file — every call here maps
// one-to-one onto a struct / field / method declared there.
fun main(args: Array<String>) {
    // The generated by-value constructors allocate INTO a MemScope, so every
    // Point/Rect we create lives for the duration of this block and is freed
    // when it ends. `Point()` / `Rect()` are MemScope extension factories (see
    // the generated companion objects), in scope thanks to the imports above.
    memScoped {
        // A 2x3 rectangle at the origin. `origin` is a Point-VALUED field, so its
        // accessors are `origin()` (get, needs a MemScope to allocate the returned
        // Point into) / `_origin(value)` (set, no allocation needed) -- NOT a Kotlin
        // `var` property. A getter that allocates can't be an ordinary property
        // getter (no way to thread a MemScope through `rect.origin`), so the
        // generator falls back to plain functions for object-valued fields. Scalar
        // fields (width, height below; x, y on Point) need no allocation and DO stay
        // ordinary `var` properties.
        val rect = Rect()
        rect._origin(Point().apply { x = 0.0; y = 0.0 })
        rect.width = 2.0
        rect.height = 3.0
        println("Rect area: ${rect.area()}")
        println("Rect origin: (${rect.origin()!!.x}, ${rect.origin()!!.y})")

        // distanceTo takes the other Point by const-ref in C++ -> a plain Kotlin
        // parameter here; the classic 3-4-5 right triangle gives 5.0.
        val a = Point().apply { x = 0.0; y = 0.0 }
        val b = Point().apply { x = 3.0; y = 4.0 }
        println("distance (0,0)->(3,4): ${a.distanceTo(b)}")

        // center() returns a Point BY VALUE; the binding constructs it into this
        // same MemScope and hands it back.
        val center = rect.center()
        println("center: (${center.x}, ${center.y})")
    }
}
