/*
 * Copyright 2026 Jason Monk
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.monkopedia.krapper

import kotlinx.serialization.Serializable

/**
 * The binding index — krapper's own answers about what it just emitted, written alongside the
 * generated tree as `krapped/binding-index.json` (#186 brick B1).
 *
 * **Why this exists.** The kplusplus compiler plugin needs to know which Kotlin class a C++ spec
 * became, so it can refine `cppVector<Int>()` to the concrete binding. Today it *re-derives* that
 * name by hand, reimplementing krapper's mangling in a second place with nothing checking the two
 * against each other — and the two already disagree (#206: krapper maps a pointer `*` to `_P`,
 * the plugin's copy maps it to `_`, so `std::vector<int*>` names two different classes). Every
 * name in here is **read off the emitted model**, never recomputed, so consuming this file
 * replaces the second implementation rather than adding a third.
 *
 * **Determinism (§5 D1).** Every collection is sorted by a stable key and no absolute host path
 * appears anywhere — the same rule the generated forcing headers already follow (#86). For a
 * fixed (tool build, config, headers, request set) the bytes are identical regardless of the
 * order requests arrived in.
 *
 * **This is a build artifact, not a committed seed.** It is regenerated by every sync and is
 * gitignored like the rest of `krapped/` (only bootstrap-necessary text is committed — see
 * `clangwalk/.gitignore`). It is a file rather than only an RPC because a file can be a declared
 * Gradle task input, works in the IDE with no process running, and works when the daemon is off.
 */
@Serializable
data class BindingIndex(
    /**
     * Bumped on any incompatible shape change. A consumer that does not recognise the version
     * MUST fall back to its previous behaviour rather than failing — an index it cannot read is
     * not worse than the no-index world it already handles.
     */
    val schemaVersion: Int = SCHEMA_VERSION,
    /**
     * Identity of the run that produced this index. Stable for identical inputs and carries no
     * host paths or timestamps, so it is safe to diff and safe to use as a cache key.
     */
    val runId: String,
    /** The configured root package the bindings were nested under, or null when unset. */
    val rootPackage: String? = null,
    /** Every emitted binding, sorted by [BindingRef.spec]. */
    val bindings: List<BindingRef> = emptyList(),
    /**
     * Every `@CppTemplate` facade emitted, sorted by [TemplateFacadeRef.base].
     *
     * Empty in B1: the facade surface is computed inside `KotlinWriter` and is not currently
     * reachable from the emit site. It is declared here so the schema does not change shape when
     * B2 gains the consumer that needs it.
     */
    val templates: List<TemplateFacadeRef> = emptyList(),
    /**
     * Kotlin fully-qualified name to C++ spelling — krapper's own table, sorted by key.
     *
     * This is what replaces the hand-maintained 4-entry primitive table in the compiler plugin
     * (`CppVectorMapping.kt:176-182`), which today knows only Int/Long/Double/Float.
     */
    val kotlinTypeMap: Map<String, String> = emptyMap(),
    /**
     * The drop ledger as structured diagnostics, sorted. Each carries severity, the C++ symbol,
     * a `file:line:col` location, the phase that dropped it, and a consumer-facing hint — so a
     * consumer can say *why* a binding is absent instead of only that it is.
     */
    val drops: List<Diagnostic> = emptyList()
) {
    companion object {
        /** Increment on any incompatible change to the shape above. */
        const val SCHEMA_VERSION: Int = 1

        /** The file name, relative to the module's generated `krapped/` root. */
        const val FILE_NAME: String = "binding-index.json"

        /**
         * Build an index with every collection in canonical order.
         *
         * The determinism contract (§5 D1) says the emitted bytes must not depend on the order
         * requests arrived in. That guarantee lives HERE rather than at the call site so it can
         * be tested without running a generation, and so a second producer (or the consumer
         * re-serializing) cannot canonicalize differently.
         *
         * Note [kotlinTypeMap] is collected into a [LinkedHashMap] after sorting:
         * kotlinx.serialization writes a map in iteration order, so sorting the entries is what
         * actually makes the bytes stable — a plain `associate` would not.
         */
        fun canonical(
            runId: String,
            rootPackage: String? = null,
            bindings: List<BindingRef> = emptyList(),
            templates: List<TemplateFacadeRef> = emptyList(),
            kotlinTypeMap: Map<String, String> = emptyMap(),
            drops: List<Diagnostic> = emptyList()
        ): BindingIndex = BindingIndex(
            runId = runId,
            rootPackage = rootPackage,
            // `spec` alone is not a guaranteed-unique key, so break ties on classId to keep the
            // order total — otherwise two bindings of the same spec could swap between runs.
            bindings = bindings.sortedWith(compareBy({ it.spec }, { it.classId })),
            templates = templates.sortedWith(compareBy({ it.base }, { it.pkg })),
            kotlinTypeMap = kotlinTypeMap.entries.sortedBy { it.key }
                .associateTo(LinkedHashMap()) { it.key to it.value },
            drops = drops.sortedWith(
                compareBy(
                    { it.symbol ?: "" },
                    { it.location?.toString() ?: "" },
                    { it.message }
                )
            )
        )
    }
}

/**
 * One emitted binding: the C++ spec krapper resolved, and the Kotlin class it became.
 *
 * [classId], [pkg] and [simpleName] are read from the same `type.kotlinType` the Kotlin writer
 * used to name the file it wrote. They are not recomputed here, which is the entire point.
 */
@Serializable
data class BindingRef(
    /** Canonical C++ spelling, exactly as krapper spells it — e.g. `std::vector<int>`. */
    val spec: String,
    /** Kotlin fully-qualified name of the generated binding — e.g. `std.Vector__Int`. */
    val classId: String,
    /** Package part of [classId]. */
    val pkg: String,
    /** Simple name part of [classId]. */
    val simpleName: String,
    /** Template base for a specialization — `std::vector` for `std::vector<int>` — else null. */
    val cppBase: String? = null,
    /**
     * Template arguments as krapper spells them, in declaration order.
     *
     * Empty in B1. Splitting a spec's argument list correctly needs a depth-aware parse
     * (`std::map<int, std::vector<int>>` is two args, not three), and shipping a field populated
     * by an unverified splitter is worse than shipping it empty — a consumer cannot tell a wrong
     * answer from a missing one. Declared now so the schema does not change shape in B2.
     */
    val templateArgs: List<String> = emptyList()
)

/** A `@CppTemplate` facade: the shape the plugin refines from. Populated in B2 — see above. */
@Serializable
data class TemplateFacadeRef(
    val base: String,
    val prefix: String,
    val pkg: String,
    val arity: Int
)
