/*
 * Copyright 2026 Jason Monk
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.monkopedia.krapper

import kotlinx.serialization.Serializable

/**
 * The binding index — krapper's own answers about what it just emitted, written alongside the
 * generated tree as `krapped/binding-index.json` (#186 brick B1).
 *
 * **Why this exists.** The kplusplus compiler plugin needs to know which Kotlin class a C++ spec
 * became, so it can refine `cppVector<Int>()` to the concrete binding. Today it *re-derives* that
 * name by hand, reimplementing krapper's mangling in a second place with nothing checking the two
 * against each other — and the two already disagree (#206: krapper maps a pointer `*` to `_P`,
 * the plugin's copy maps it to `_`, so `std::vector<int*>` names two different classes). Every
 * name in here is **read off the emitted model**, never recomputed, so consuming this file
 * replaces the second implementation rather than adding a third.
 *
 * **Determinism (§5 D1).** Every collection is sorted by a stable key, so for a fixed
 * (tool build, config, headers, request set) the bytes are identical regardless of the order
 * requests arrived in. Paths under the output tree are relativized (the same rule the generated
 * forcing headers follow, #86), which makes the file **checkout-independent**.
 *
 * It is NOT machine-independent: drop locations pointing at TOOLCHAIN headers (`/usr/lib/llvm-22`,
 * the gcc include dir) stay absolute by design — see [Companion.relativizePath]. Two machines with
 * different LLVM or libstdc++ minor versions produce different bytes there. That is acceptable
 * because the index is a build artifact regenerated per sync, never a committed seed; do not lean
 * on it as a cross-machine fingerprint.
 *
 * **This is a build artifact, not a committed seed.** It is regenerated by every sync and is
 * gitignored like the rest of `krapped/` (only bootstrap-necessary text is committed — see
 * `clangwalk/.gitignore`). It is a file rather than only an RPC because a file can be a declared
 * Gradle task input, works in the IDE with no process running, and works when the daemon is off.
 */
@Serializable
data class BindingIndex(
    /**
     * Bumped on any incompatible shape change. A consumer that does not recognise the version
     * MUST fall back to its previous behaviour rather than failing — an index it cannot read is
     * not worse than the no-index world it already handles.
     */
    val schemaVersion: Int = SCHEMA_VERSION,
    /**
     * Identity of the run that produced this index. Stable for identical inputs and carries no
     * host paths or timestamps, so it is safe to diff and safe to use as a cache key.
     */
    val runId: String,
    /** The configured root package the bindings were nested under, or null when unset. */
    val rootPackage: String? = null,
    /** Every emitted binding, sorted by [BindingRef.spec]. */
    val bindings: List<BindingRef> = emptyList(),
    /**
     * Every `@CppTemplate` facade emitted, sorted by [TemplateFacadeRef.base].
     *
     * Empty in B1: the facade surface is computed inside `KotlinWriter` and is not currently
     * reachable from the emit site. It is declared here so the schema does not change shape when
     * B2 gains the consumer that needs it.
     */
    val templates: List<TemplateFacadeRef> = emptyList(),
    /**
     * Kotlin fully-qualified name to C++ spelling — krapper's own table, sorted by key.
     *
     * This is what replaces the hand-maintained 4-entry primitive table in the compiler plugin
     * (`CppVectorMapping.kt:176-182`), which today knows only Int/Long/Double/Float.
     */
    val kotlinTypeMap: Map<String, String> = emptyMap(),
    /**
     * The drop ledger as structured diagnostics, sorted. Each carries severity, the C++ symbol,
     * a `file:line:col` location, the phase that dropped it, and a consumer-facing hint — so a
     * consumer can say *why* a binding is absent instead of only that it is.
     */
    val drops: List<Diagnostic> = emptyList()
) {
    companion object {
        /** Increment on any incompatible change to the shape above. */
        const val SCHEMA_VERSION: Int = 1

        /** The file name, relative to the module's generated `krapped/` root. */
        const val FILE_NAME: String = "binding-index.json"

        /**
         * Rewrite an absolute [path] as relative to [base], or return it unchanged when it does
         * not sit under a shared root.
         *
         * Purpose: the index must not carry a path that depends on WHERE THE CHECKOUT LIVES
         * (§5 D1) — a tree generated in one checkout has to be byte-identical to one generated in
         * another, and `/home/<someone>/git/...` is neither reproducible nor meaningful to a
         * consumer. Same rule the generated forcing headers already follow (#86).
         *
         * **This does not make every path relative, and deliberately so.** A path sharing nothing
         * with [base] but the filesystem root — a system header under `/usr/lib/llvm-22`, say —
         * is returned unchanged, because rewriting it into a long `../../..` chain would be less
         * useful and no more portable. So the emitted index still contains absolute paths for
         * toolchain headers: it is **checkout-independent, not machine-independent**. Two boxes
         * with different LLVM or libstdc++ minor versions would produce different bytes there.
         *
         * Kept pure and string-based so it is testable without a filesystem.
         */
        fun relativizePath(path: String, base: String): String {
            if (!path.startsWith("/") || !base.startsWith("/")) return path
            val from = base.trim('/').split("/").filter { it.isNotEmpty() }
            val to = path.trim('/').split("/").filter { it.isNotEmpty() }
            var shared = 0
            while (shared < from.size && shared < to.size && from[shared] == to[shared]) shared++
            // Nothing in common beyond the filesystem root: relativizing would produce a path
            // longer and less useful than the original (a system header, typically). Leave it.
            if (shared == 0) return path
            val ups = List(from.size - shared) { ".." }
            val parts = ups + to.drop(shared)
            // path == base: every segment is shared and nothing remains. "" is not a path;
            // "." is the relative spelling of "the base itself".
            return if (parts.isEmpty()) "." else parts.joinToString("/")
        }

        /**
         * Build an index with every collection in canonical order.
         *
         * The determinism contract (§5 D1) says the emitted bytes must not depend on the order
         * requests arrived in. That guarantee lives HERE rather than at the call site so it can
         * be tested without running a generation, and so a second producer (or the consumer
         * re-serializing) cannot canonicalize differently.
         *
         * Note [kotlinTypeMap] is collected into a [LinkedHashMap] after sorting:
         * kotlinx.serialization writes a map in iteration order, so sorting the entries is what
         * actually makes the bytes stable — a plain `associate` would not.
         */
        fun canonical(
            runId: String,
            rootPackage: String? = null,
            bindings: List<BindingRef> = emptyList(),
            templates: List<TemplateFacadeRef> = emptyList(),
            kotlinTypeMap: Map<String, String> = emptyMap(),
            drops: List<Diagnostic> = emptyList()
        ): BindingIndex = BindingIndex(
            runId = runId,
            rootPackage = rootPackage,
            // `spec` alone is not a guaranteed-unique key, so break ties on classId to keep the
            // order total — otherwise two bindings of the same spec could swap between runs.
            bindings = bindings.sortedWith(compareBy({ it.spec }, { it.classId })),
            templates = templates.sortedWith(compareBy({ it.base }, { it.pkg })),
            kotlinTypeMap = kotlinTypeMap.entries.sortedBy { it.key }
                .associateTo(LinkedHashMap()) { it.key to it.value },
            // severity and phase are included because the ledger genuinely emits several
            // combinations (e.g. INFO/DEDUP alongside WARNING/RESOLVE), so without them two
            // drops can tie on every compared key while differing in the emitted bytes — which
            // would make run-to-run stability a property of the input order rather than of this
            // sort. With them the ordering is total over everything Diagnostic carries.
            drops = drops.sortedWith(
                compareBy(
                    { it.symbol ?: "" },
                    { it.location?.toString() ?: "" },
                    { it.phase?.name ?: "" },
                    { it.severity.name },
                    { it.message },
                    { it.hint ?: "" }
                )
            )
        )
    }
}

/**
 * One emitted binding: the C++ spec krapper resolved, and the Kotlin class it became.
 *
 * [classId], [pkg] and [simpleName] are read from the same `type.kotlinType` the Kotlin writer
 * used to name the file it wrote. They are not recomputed here, which is the entire point.
 */
@Serializable
data class BindingRef(
    /** Canonical C++ spelling, exactly as krapper spells it — e.g. `std::vector<int>`. */
    val spec: String,
    /** Kotlin fully-qualified name of the generated binding — e.g. `std.Vector__Int`. */
    val classId: String,
    /** Package part of [classId]. */
    val pkg: String,
    /** Simple name part of [classId]. */
    val simpleName: String,
    /** Template base for a specialization — `std::vector` for `std::vector<int>` — else null. */
    val cppBase: String? = null,
    // NOTE for B2: the design (§4.1) also declares `factory` and `holderFactory` — the companion
    // default-ctor and `<name>_Holder` factory names. They are NOT declared here because B1 has no
    // way to read them: they are decided by the Kotlin writer's emit, not present on the resolved
    // model. Adding them in B2 WILL change this class's shape, unlike `templates`/`templateArgs`
    // which are declared-but-empty precisely so they do not. Recording it so that shape change is
    // expected rather than discovered.
    /**
     * Template arguments as krapper spells them, in declaration order.
     *
     * Empty in B1. Splitting a spec's argument list correctly needs a depth-aware parse
     * (`std::map<int, std::vector<int>>` is two args, not three), and shipping a field populated
     * by an unverified splitter is worse than shipping it empty — a consumer cannot tell a wrong
     * answer from a missing one. Declared now so the schema does not change shape in B2.
     */
    val templateArgs: List<String> = emptyList()
)

/** A `@CppTemplate` facade: the shape the plugin refines from. Populated in B2 — see above. */
@Serializable
data class TemplateFacadeRef(val base: String, val prefix: String, val pkg: String, val arity: Int)
